### ISSUE TITLE
Arrays causing polygon to soft crash

### ISSUE THREAD

**Issue by NekaouMike** [PolygonDB/PolygonDB#16]
**Describe the bug**
Polygon hanging/ possibly memory leaking when dealing with arrays
**To Reproduce**
Record array data to a database a for a bit

**Expected behavior**
It should just be inserting the arrays with NO issues

**Desktop (please complete the following information):**
Win 11 running V1.5 amd64 
Node JS V17

**Comment by JewishLewish** [comment]
I found the problem for this. 
This is really much an extension of Github Issue #12 

Now that ``value`` can accept any kind of variable (no longer just 'string'), it creates a problem with ``record`` and ``append`` from functioning properly. 

value: "['test']" and value: ['test'] can result in different outputs 

As for memory leaking, I haven't seen to detect any.

**Comment by NekaouMike** [comment]
I just knew that it would hang.

**Comment by JewishLewish** [comment]
> I just knew that it would hang.

v1.5.1 Should really much take of the problem for record and append. 
Since I want to make it so you no longer need to put value in string form. 

Ex.

Before:
`` 'value' : '{"Example" : "Hello world"}' ``

After:

`` 'value' : {"Example : "Hello world"} ``

Edit:
Plus in benchmarks, it has shown to actually cut down speeds and make it faster

**Comment by NekaouMike** [comment]
You did check with [ ] too right?

**Comment by JewishLewish** [comment]
Works.

**Comment by NekaouMike** [comment]
You made things WORSE. Like actively you made things unusable when getting data back...

**Comment by NekaouMike** [comment]
Like I have to revert my version

**Comment by NekaouMike** [comment]
```js
db.record("database",0,"column",[])
```
Stores `'[]'` to the DB

**Comment by JewishLewish** [comment]
Can you share me the record function?

**Comment by NekaouMike** [comment]
https://github.com/NekaouMike/PolyConJS/blob/dd042ad4dba5fa676e336c7bdf1c88a75afcc61e/main.js#L22

**Comment by JewishLewish** [comment]
It is interesting because on Python, this code works:

```py
ws.send(json.dumps(
    {
        'password': 'Better_Password', 
        'dbname': 'ExampleDB',
        'location' :'data.company',
        'action' : 'record',
        'value' : {"CompanyName":"COMBOT", "Years_of_Service": 1962, "Workers":["Mike", "Tite"]}
    }
))
```

Make sure value is not in the form of string.

**Comment by NekaouMike** [comment]
send just `[]`

**Comment by JewishLewish** [comment]
As of the latest version of Polygon DB, works.

**Comment by JewishLewish** [comment]
```py
ws.send(json.dumps(
    {
        'password': 'Better_Password', 
        'dbname': 'ExampleDB',
        'location' :'data.balance',
        'action' : 'record',
        'value' : []
    }
))
```

This code works and outputs a simple ``[]``
I will look into getting any final minor updates into Polygon v1.5.5 before I fully get into Polygon v1.6 because I don't want to backtrack

**Comment by JewishLewish** [comment]
Should be fixed.
